
import { Exercise, MuscleGroup } from './types';

export const DEFAULT_EXERCISES: Exercise[] = [
  // Pecho (20)
  { id: 'c1', name: 'Press de Banca con Barra', muscleGroup: MuscleGroup.CHEST },
  { id: 'c2', name: 'Press de Banca con Mancuernas', muscleGroup: MuscleGroup.CHEST },
  { id: 'c3', name: 'Press Inclinado con Barra', muscleGroup: MuscleGroup.CHEST },
  { id: 'c4', name: 'Press Inclinado con Mancuernas', muscleGroup: MuscleGroup.CHEST },
  { id: 'c5', name: 'Press Declinado con Barra', muscleGroup: MuscleGroup.CHEST },
  { id: 'c6', name: 'Press de Pecho en Máquina', muscleGroup: MuscleGroup.CHEST },
  { id: 'c7', name: 'Aperturas en Polea Alta', muscleGroup: MuscleGroup.CHEST },
  { id: 'c8', name: 'Aperturas con Mancuernas', muscleGroup: MuscleGroup.CHEST },
  { id: 'c9', name: 'Fondos de Pecho (Dips)', muscleGroup: MuscleGroup.CHEST },
  { id: 'c10', name: 'Contractor (Pec Deck)', muscleGroup: MuscleGroup.CHEST },
  { id: 'c11', name: 'Flexiones de Brazos (Push Ups)', muscleGroup: MuscleGroup.CHEST },
  { id: 'c12', name: 'Press Landmine', muscleGroup: MuscleGroup.CHEST },
  { id: 'c13', name: 'Cruces de Polea Bajas', muscleGroup: MuscleGroup.CHEST },
  { id: 'c14', name: 'Press de Pecho Hammer Strength', muscleGroup: MuscleGroup.CHEST },
  { id: 'c15', name: 'Press Arnold para Pecho', muscleGroup: MuscleGroup.CHEST },
  { id: 'c16', name: 'Aperturas en Máquina', muscleGroup: MuscleGroup.CHEST },
  { id: 'c17', name: 'Press Svend', muscleGroup: MuscleGroup.CHEST },
  { id: 'c18', name: 'Flexiones con Diamante', muscleGroup: MuscleGroup.CHEST },
  { id: 'c19', name: 'Press de Banca Agarre Cerrado', muscleGroup: MuscleGroup.CHEST },
  { id: 'c20', name: 'Pull-over con Mancuerna', muscleGroup: MuscleGroup.CHEST },

  // Espalda (20)
  { id: 'b1', name: 'Remo con Barra', muscleGroup: MuscleGroup.BACK },
  { id: 'b2', name: 'Remo con Mancuerna a una Mano', muscleGroup: MuscleGroup.BACK },
  { id: 'b3', name: 'Dominadas (Pull Ups)', muscleGroup: MuscleGroup.BACK },
  { id: 'b4', name: 'Jalón al Pecho (Agarre Ancho)', muscleGroup: MuscleGroup.BACK },
  { id: 'b5', name: 'Remo en Polea Baja', muscleGroup: MuscleGroup.BACK },
  { id: 'b6', name: 'Remo en T', muscleGroup: MuscleGroup.BACK },
  { id: 'b7', name: 'Remo Pendlay', muscleGroup: MuscleGroup.BACK },
  { id: 'b8', name: 'Face Pulls para Espalda', muscleGroup: MuscleGroup.BACK },
  { id: 'b9', name: 'Peso Muerto Convencional', muscleGroup: MuscleGroup.BACK },
  { id: 'b10', name: 'Hiperextensiones Lumbares', muscleGroup: MuscleGroup.BACK },
  { id: 'b11', name: 'Pullover en Polea Alta', muscleGroup: MuscleGroup.BACK },
  { id: 'b12', name: 'Jalón con Agarre Estrecho', muscleGroup: MuscleGroup.BACK },
  { id: 'b13', name: 'Remo en Máquina (Chest Supported)', muscleGroup: MuscleGroup.BACK },
  { id: 'b14', name: 'Dominadas con Peso', muscleGroup: MuscleGroup.BACK },
  { id: 'b15', name: 'Remo Seal', muscleGroup: MuscleGroup.BACK },
  { id: 'b16', name: 'Remo Meadows', muscleGroup: MuscleGroup.BACK },
  { id: 'b17', name: 'Remo con Soporte en Pecho', muscleGroup: MuscleGroup.BACK },
  { id: 'b18', name: 'Good Mornings', muscleGroup: MuscleGroup.BACK },
  { id: 'b19', name: 'Remo Invertido', muscleGroup: MuscleGroup.BACK },
  { id: 'b20', name: 'Rack Pulls', muscleGroup: MuscleGroup.BACK },

  // Piernas (18) - Sin glúteos
  { id: 'l1', name: 'Sentadilla con Barra Trasera', muscleGroup: MuscleGroup.LEGS },
  { id: 'l2', name: 'Sentadilla Frontal', muscleGroup: MuscleGroup.LEGS },
  { id: 'l3', name: 'Prensa de Piernas', muscleGroup: MuscleGroup.LEGS },
  { id: 'l4', name: 'Extensión de Cuádriceps', muscleGroup: MuscleGroup.LEGS },
  { id: 'l5', name: 'Curl Femoral Sentado', muscleGroup: MuscleGroup.LEGS },
  { id: 'l6', name: 'Curl Femoral Tumbado', muscleGroup: MuscleGroup.LEGS },
  { id: 'l7', name: 'Sentadilla Búlgara', muscleGroup: MuscleGroup.LEGS },
  { id: 'l8', name: 'Zancadas Caminando (Lunges)', muscleGroup: MuscleGroup.LEGS },
  { id: 'l9', name: 'Elevación de Talones de Pie', muscleGroup: MuscleGroup.LEGS },
  { id: 'l10', name: 'Elevación de Talones Sentado', muscleGroup: MuscleGroup.LEGS },
  { id: 'l11', name: 'Peso Muerto Rumano', muscleGroup: MuscleGroup.LEGS },
  { id: 'l12', name: 'Sentadilla Hack', muscleGroup: MuscleGroup.LEGS },
  { id: 'l14', name: 'Peso Muerto Sumo', muscleGroup: MuscleGroup.LEGS },
  { id: 'l15', name: 'Sentadilla Goblet', muscleGroup: MuscleGroup.LEGS },
  { id: 'l18', name: 'Prensa Inclinada', muscleGroup: MuscleGroup.LEGS },
  { id: 'l19', name: 'Step-ups', muscleGroup: MuscleGroup.LEGS },
  { id: 'l21', name: 'Sissy Squat', muscleGroup: MuscleGroup.LEGS },
  { id: 'l22', name: 'Nórdicos (Hamstrings)', muscleGroup: MuscleGroup.LEGS },

  // Glúteos (12)
  { id: 'g1', name: 'Hip Thrust con Barra', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g2', name: 'Puente de Glúteo', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g3', name: 'Patada de Glúteo en Polea', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g4', name: 'Abducción de Cadera en Máquina', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g5', name: 'Abducción de Cadera en Polea', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g6', name: 'Clamshells con Banda', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g7', name: 'Frog Pumps', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g8', name: 'Sentadilla Sumo con Mancuerna', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g9', name: 'Peso Muerto con Piernas Rígidas', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g10', name: 'Hiperextensiones (Enfoque Glúteo)', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g11', name: 'Caminata Lateral con Banda', muscleGroup: MuscleGroup.GLUTEOS },
  { id: 'g12', name: 'Step-up Lateral', muscleGroup: MuscleGroup.GLUTEOS },

  // Hombros (20)
  { id: 's1', name: 'Press Militar con Barra', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's2', name: 'Press de Hombros con Mancuernas', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's3', name: 'Elevaciones Laterales con Mancuernas', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's4', name: 'Elevaciones Frontales con Mancuernas', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's5', name: 'Pájaros (Reverse Pec Deck)', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's6', name: 'Press Arnold', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's7', name: 'Remo al Mentón', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's8', name: 'Encogimientos con Barra (Shrugs)', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's9', name: 'Encogimientos con Mancuernas', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's10', name: 'Face Pulls (Enfoque Hombro)', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's11', name: 'Push Press con Barra', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's12', name: 'Elevaciones Laterales en Máquina', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's13', name: 'Elevaciones Laterales en Polea', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's14', name: 'Press Militar Sentado', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's15', name: 'Vuelos Posteriores en Polea', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's16', name: 'Remo al Mentón con Mancuernas', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's17', name: 'Landmine Press a una Mano', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's18', name: 'Y-Raise', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's19', name: 'Handstand Push Ups', muscleGroup: MuscleGroup.SHOULDERS },
  { id: 's20', name: 'Press de Hombros Hammer', muscleGroup: MuscleGroup.SHOULDERS },

  // Brazos (20)
  { id: 'a1', name: 'Curl de Bíceps con Barra EZ', muscleGroup: MuscleGroup.ARMS },
  { id: 'a2', name: 'Curl de Bíceps con Mancuernas', muscleGroup: MuscleGroup.ARMS },
  { id: 'a3', name: 'Curl Martillo (Hammer Curl)', muscleGroup: MuscleGroup.ARMS },
  { id: 'a4', name: 'Curl Predicador', muscleGroup: MuscleGroup.ARMS },
  { id: 'a5', name: 'Curl de Bíceps en Polea', muscleGroup: MuscleGroup.ARMS },
  { id: 'a6', name: 'Extensión Tríceps Polea (Cuerda)', muscleGroup: MuscleGroup.ARMS },
  { id: 'a7', name: 'Extensión Tríceps Polea (Barra)', muscleGroup: MuscleGroup.ARMS },
  { id: 'a8', name: 'Press Francés (Skullcrushers)', muscleGroup: MuscleGroup.ARMS },
  { id: 'a9', name: 'Extensión Tras Nuca con Mancuerna', muscleGroup: MuscleGroup.ARMS },
  { id: 'a10', name: 'Fondos en Paralelas (Tríceps)', muscleGroup: MuscleGroup.ARMS },
  { id: 'a11', name: 'Press de Banca Agarre Estrecho', muscleGroup: MuscleGroup.ARMS },
  { id: 'a12', name: 'Curl Concentrado', muscleGroup: MuscleGroup.ARMS },
  { id: 'a13', name: 'Curl de Bíceps en Inclinado', muscleGroup: MuscleGroup.ARMS },
  { id: 'a14', name: 'Curl Zottman', muscleGroup: MuscleGroup.ARMS },
  { id: 'a15', name: 'Patada de Tríceps', muscleGroup: MuscleGroup.ARMS },
  { id: 'a16', name: 'Fondos entre Bancos', muscleGroup: MuscleGroup.ARMS },
  { id: 'a17', name: 'Curl de Bíceps en Máquina', muscleGroup: MuscleGroup.ARMS },
  { id: 'a18', name: 'Curl de Bíceps Platino', muscleGroup: MuscleGroup.ARMS },
  { id: 'a19', name: 'Extensión de Tríceps en Máquina', muscleGroup: MuscleGroup.ARMS },
  { id: 'a20', name: 'Spider Curls', muscleGroup: MuscleGroup.ARMS },

  // Core (20)
  { id: 'cr1', name: 'Plancha Abdominal', muscleGroup: MuscleGroup.CORE },
  { id: 'cr2', name: 'Elevación de Piernas Colgado', muscleGroup: MuscleGroup.CORE },
  { id: 'cr3', name: 'Crunch en Polea Alta', muscleGroup: MuscleGroup.CORE },
  { id: 'cr4', name: 'Giro Ruso (Russian Twist)', muscleGroup: MuscleGroup.CORE },
  { id: 'cr5', name: 'Rueda Abdominal (Ab Wheel)', muscleGroup: MuscleGroup.CORE },
  { id: 'cr6', name: 'Bicicleta Abdominal', muscleGroup: MuscleGroup.CORE },
  { id: 'cr7', name: 'V-Ups', muscleGroup: MuscleGroup.CORE },
  { id: 'cr8', name: 'Dead Bug', muscleGroup: MuscleGroup.CORE },
  { id: 'cr9', name: 'Bird Dog', muscleGroup: MuscleGroup.CORE },
  { id: 'cr10', name: 'Escaladores (Mountain Climbers)', muscleGroup: MuscleGroup.CORE },
  { id: 'cr11', name: 'Woodchopper en Polea', muscleGroup: MuscleGroup.CORE },
  { id: 'cr12', name: 'L-Sit', muscleGroup: MuscleGroup.CORE },
  { id: 'cr13', name: 'Crunch Abdominal Clásico', muscleGroup: MuscleGroup.CORE },
  { id: 'cr14', name: 'Toes to Bar', muscleGroup: MuscleGroup.CORE },
  { id: 'cr15', name: 'Elevación de Rodillas al Pecho', muscleGroup: MuscleGroup.CORE },
  { id: 'cr16', name: 'Plancha Lateral', muscleGroup: MuscleGroup.CORE },
  { id: 'cr17', name: 'Heel Touches', muscleGroup: MuscleGroup.CORE },
  { id: 'cr18', name: 'Bear Crawl', muscleGroup: MuscleGroup.CORE },
  { id: 'cr19', name: 'Abdominales en Pelota Suiza', muscleGroup: MuscleGroup.CORE },
  { id: 'cr20', name: 'Flexión Lateral con Mancuerna', muscleGroup: MuscleGroup.CORE },
];

export const MUSCLE_GROUPS = Object.values(MuscleGroup);
